# Generated by Django 5.2.4 on 2025-11-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('pointId', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
                ('pointEarned', models.IntegerField(blank=True, db_column='pointEarned', null=True)),
                ('pointUsed', models.IntegerField(blank=True, db_column='pointUsed', null=True)),
                ('todayPoint', models.IntegerField(blank=True, db_column='todayPoint', null=True)),
                ('holdingPoint', models.IntegerField(blank=True, db_column='holdingPoint', null=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='users.user')),
            ],
            options={
                'db_table': 'Point',
            },
        ),
    ]
