# Generated by Django 5.2.4 on 2025-07-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_point_pointused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='placeId',
        ),
        migrations.AddField(
            model_name='point',
            name='content',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
