# Generated by Django 5.2.4 on 2025-07-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(db_column='placeName', max_length=255)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('placeImage', models.URLField(blank=True, db_column='placeImage', null=True)),
            ],
            options={
                'db_table': 'Place',
            },
        ),
        migrations.CreateModel(
            name='FavoritePlace',
            fields=[
                ('favoritePlaceId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('placeId', models.ForeignKey(db_column='placeId', on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'db_table': 'FavoritePlace',
                'unique_together': {('placeId', 'userId')},
            },
        ),
    ]
