# Generated by Django 5.2.4 on 2025-07-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.JSONField(default=list),
        ),
    ]
