# Generated by Django 5.2.4 on 2025-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
