# Generated by Django 5.2.4 on 2025-11-06 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, max_length=255, null=True)),
                ('profileImage', models.CharField(blank=True, db_column='profileImage', max_length=500, null=True)),
                ('fcm_token', models.CharField(max_length=255, null=True)),
                ('auth', models.OneToOneField(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('representBadge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representing_users', to='badges.badge')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_link', to='users.user')),
            ],
            options={
                'db_table': 'FriendLink',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], db_column='status', default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closeFriend', models.BooleanField(default=False)),
                ('user_small', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('user_large', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='users.user')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='users.user')),
            ],
            options={
                'db_table': 'Friendship',
                'indexes': [models.Index(fields=['status', 'user_small'], name='fx_status_small'), models.Index(fields=['status', 'user_large'], name='fx_status_large')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user_small__lt', models.F('user_large'))), name='friendship_chk_order'), models.UniqueConstraint(fields=('user_small', 'user_large'), name='friendship_uq_pair')],
            },
        ),
    ]
