# Generated by Django 5.2.4 on 2025-07-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborStatus', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], db_column='neighborStatus', help_text='친구 상태', max_length=10, null=True)),
                ('profileImage', models.CharField(blank=True, db_column='profileImage', max_length=500, null=True)),
                ('receiverId', models.ForeignKey(blank=True, db_column='receiverId', help_text='친구 요청 받은 사람', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to='users.user')),
                ('requesterId', models.ForeignKey(blank=True, db_column='requesterId', help_text='친구 요청 보낸 사람', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_requests', to='users.user')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
