# Generated by Django 5.2.4 on 2025-08-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_authuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='authUser',
            new_name='auth',
        ),
    ]
