# Generated by Django 5.2.4 on 2025-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_authuser_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='closeFriend',
            field=models.BooleanField(default=False),
        ),
    ]
