# Generated by Django 5.2.4 on 2025-08-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_friendship_closefriend'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FriendLink',
            },
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_large',
            field=models.BigIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_small',
            field=models.BigIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status', 'user_small'], name='fx_status_small'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status', 'user_large'], name='fx_status_large'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user_small__lt', models.F('user_large'))), name='friendship_chk_order'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user_small', 'user_large'), name='friendship_uq_pair'),
        ),
        migrations.AddField(
            model_name='friendlink',
            name='issuer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_link', to='users.user'),
        ),
    ]
