# Generated by Django 5.2.4 on 2025-09-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_userbadge_createdat'),
        ('users', '0008_friendlink_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='representBadge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representing_users', to='badges.userbadge'),
        ),
    ]
