# Generated by Django 5.2.4 on 2025-11-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_fcm_token_alter_user_representbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
