# Generated by Django 5.2.4 on 2025-11-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_fcm_token_user_apple_sub'),
        ('users', '0011_user_apple_sub'),
    ]

    operations = [
    ]
