# Generated by Django 5.2.4 on 2025-11-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20251105_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apple_sub',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
