# Generated by Django 5.2.4 on 2025-11-06 16:52

import albums.models
import albums.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumId', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoId', models.BigAutoField(primary_key=True, serialize=False)),
                ('feelings', models.CharField(blank=True, max_length=255, null=True)),
                ('weather', models.CharField(blank=True, max_length=255, null=True)),
                ('photoContent', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('photoUrl', models.ImageField(default='photos/default.jpg', max_length=2048, storage=albums.storages.PublicMediaStorage, upload_to=albums.models.album_photo_path)),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
