# Generated by Django 5.2.4 on 2025-11-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('challenges', '0001_initial'),
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='placeId',
            field=models.ForeignKey(db_column='placeId', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='places.place'),
        ),
        migrations.AddField(
            model_name='album',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='users.user'),
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(db_column='albumId', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.album'),
        ),
        migrations.AddField(
            model_name='photo',
            name='challengeAttemptId',
            field=models.ForeignKey(blank=True, db_column='challengeAttemptId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='challenges.challengeattempt'),
        ),
        migrations.AddField(
            model_name='album',
            name='representativePhotoId',
            field=models.ForeignKey(blank=True, db_column='representativePhotoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_albums', to='albums.photo'),
        ),
    ]
