# Generated by Django 5.2.4 on 2025-07-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='albumId',
            new_name='album',
        ),
        migrations.AddField(
            model_name='photo',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
