# Generated by Django 5.2.4 on 2025-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_albumid_photo_album_photo_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoUrl',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
