# Generated by Django 5.2.4 on 2025-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_photo_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
