# Generated by Django 5.2.4 on 2025-07-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_photo_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoUrl',
            field=models.CharField(default='image.heic', max_length=500),
        ),
    ]
