# Generated by Django 5.2.4 on 2025-07-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_photo_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoContent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
