# Generated by Django 5.2.4 on 2025-07-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_photo_photocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoContent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoUrl',
            field=models.CharField(default='image.heic', max_length=1000),
        ),
    ]
