# Generated by Django 5.2.4 on 2025-07-30 13:16

import albums.models
import albums.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_photo_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoUrl',
            field=models.ImageField(default='photos/default.jpg', max_length=2048, storage=albums.storages.PublicMediaStorage, upload_to=albums.models.album_photo_path),
        ),
    ]
