# Generated by Django 5.2.4 on 2025-08-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_photo_photourl'),
        ('challenges', '0011_alter_challengeattempt_attemptimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='challengeAttemptId',
            field=models.ForeignKey(blank=True, db_column='challengeAttemptId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='challenges.challengeattempt'),
        ),
    ]
