# Generated by Django 5.2.4 on 2025-07-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challengeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('condition1', models.CharField(blank=True, max_length=255, null=True)),
                ('condition2', models.CharField(blank=True, max_length=255, null=True)),
                ('condition3', models.CharField(blank=True, max_length=255, null=True)),
                ('placeId', models.ForeignKey(db_column='placeId', on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'db_table': 'Challenge',
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('challengeAttemptId', models.BigAutoField(primary_key=True, serialize=False)),
                ('attemptDate', models.DateTimeField(blank=True, null=True)),
                ('attemptImage', models.URLField(blank=True, null=True)),
                ('resultComment', models.CharField(blank=True, max_length=255, null=True)),
                ('attemptResult', models.BooleanField(null=True)),
                ('challengeId', models.ForeignKey(db_column='challengeId', on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ChallengeAttempt',
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttemptUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeAttemptId', models.ForeignKey(db_column='challgeAttemptId', on_delete=django.db.models.deletion.CASCADE, to='challenges.challengeattempt')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ChallengeAttemptUser',
            },
        ),
    ]
