# Generated by Django 5.2.4 on 2025-11-06 16:52

import challenges.models
import challenges.storages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challengeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('point', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('condition1', models.CharField(blank=True, max_length=255, null=True)),
                ('condition2', models.CharField(blank=True, max_length=255, null=True)),
                ('condition3', models.CharField(blank=True, max_length=255, null=True)),
                ('placeId', models.ForeignKey(db_column='placeId', on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'db_table': 'Challenge',
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('challengeAttemptId', models.BigAutoField(primary_key=True, serialize=False)),
                ('attemptDate', models.CharField(blank=True, max_length=255, null=True)),
                ('attemptImage', models.ImageField(blank=True, max_length=2048, null=True, storage=challenges.storages.PublicMediaStorage, upload_to=challenges.models.attempt_image_upload_path)),
                ('resultComment', models.TextField(blank=True, null=True)),
                ('attemptResult', models.BooleanField(null=True)),
                ('result_details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '처리 대기중'), ('PROCESSING', '처리중'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='PENDING', max_length=15)),
                ('challengeId', models.ForeignKey(db_column='challengeId', on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ChallengeAttempt',
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttemptUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeAttemptId', models.ForeignKey(db_column='challengeAttemptId', on_delete=django.db.models.deletion.CASCADE, to='challenges.challengeattempt')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ChallengeAttemptUser',
            },
        ),
    ]
