# Generated by Django 5.2.4 on 2025-07-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='attemptDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
