# Generated by Django 5.2.4 on 2025-07-17 16:11

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challengeattempt_attemptdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='attemptImage',
            field=models.ImageField(blank=True, null=True, upload_to=challenges.models.attempt_image_upload_path),
        ),
    ]
