# Generated by Django 5.2.4 on 2025-07-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challengeattempt_attemptimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='attemptImage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
