# Generated by Django 5.2.4 on 2025-07-18 02:51

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_challengeattempt_attemptimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='attemptImage',
            field=models.ImageField(blank=True, null=True, upload_to=challenges.models.user_place_attempt_path),
        ),
    ]
