# Generated by Django 5.2.4 on 2025-07-18 17:26

import albums.storages
import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_alter_challengeattempt_attemptimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='attemptImage',
            field=models.ImageField(blank=True, null=True, storage=albums.storages.PublicMediaStorage, upload_to=challenges.models.attempt_image_upload_path),
        ),
    ]
