# Generated by Django 5.2.4 on 2025-07-30 13:19

import challenges.models
import challenges.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_alter_challengeattempt_attemptimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='attemptImage',
            field=models.ImageField(blank=True, max_length=2048, null=True, storage=challenges.storages.PublicMediaStorage, upload_to=challenges.models.attempt_image_upload_path),
        ),
    ]
