# Generated by Django 5.2.4 on 2025-09-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_challengeattempt_attemptimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='status',
            field=models.CharField(choices=[('PENDING', '처리 대기중'), ('PROCESSING', '처리중'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='PENDING', max_length=15),
        ),
    ]
