# Generated by Django 5.2.4 on 2025-09-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_challengeattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
