# Generated by Django 5.2.4 on 2025-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_challengeattempt_result_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattempt',
            name='resultComment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
