# Generated by Django 5.2.4 on 2025-09-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_alter_challengeattempt_resultcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeattemptuser',
            name='challengeAttemptId',
            field=models.ForeignKey(db_column='challengeAttemptId', on_delete=django.db.models.deletion.CASCADE, to='challenges.challengeattempt'),
        ),
    ]
