# Generated by Django 5.2.4 on 2025-07-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badgeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('badgeName', models.CharField(blank=True, max_length=255, null=True)),
                ('badgeImage', models.URLField(blank=True, null=True)),
                ('condition', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Badge',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('userBadgeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('badgeId', models.ForeignKey(db_column='badgeId', on_delete=django.db.models.deletion.CASCADE, to='badges.badge')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserBadge',
                'unique_together': {('userId', 'badgeId')},
            },
        ),
    ]
